### ISSUE TITLE
Footer links should change color when hovered

### ISSUE THREAD

**Issue by nathan-rollins** [gios-asu/ASU-Web-Standards-Bootstrap#197]
As per [ASU Web Standards](https://brandguide.asu.edu/web-standards/enterprise/global-asu-footer) for global footers, normal link text should be #333333 and #666666 when hovered.

**Comment by rraub** [comment]
FYI we've used the terms `little-foot` and `big-foot` to refer to the different footer sections. However the standards now call our `little-foot` the `global footer` (which kinda makes sense, since it is required globally), and the `big-foot` is called the `Super Footer`. 

It does look like we are in compliance with the styles for the little-foot, however our links in the big-foot still could use a different color on hover like the rest of the world. Even though the [standards for the super footer](https://brandguide.asu.edu/web-standards/enterprise/super-footer#quicktabs-super_footer=2) don't define one. Also it looks like they specify a different grey for link's in the standards.
