### ISSUE TITLE
Javascript Dependencies 

### ISSUE THREAD

**Issue by cordmata** [gios-asu/ASU-Web-Standards-Bootstrap#58]
Just a question: are *all* of the dependencies listed in the read-me actually going to be a required part of the ASU standard (e.g. smoothscroll/lighteningtouch/moment)? If not, should there be a separation between baseline stylistic/functional components and add-on/optional ones?

**Comment by idmontie** [comment]
As of right now, the dependencies are strictly required.  The Web Standards JavaScript checks that they are already included in order to run.  

We will actually be reducing the dependencies in the near future so that you do not need to include them if you are not going to use certain features:

* Moment will only be required for Calendar Downloads.
* Smoothscroll will be optional.
* LigheningTouch should already be optional.
* RespondJS should be already be optional.

It should also be noted in the README.md which dependencies are required and which are optional.  I will make a separate issue for this as an Enhancement.

**Comment by cordmata** [comment]
Thanks, yes, my main concern is the strict checking that results in runtime exceptions for optional JS functionality. I just want to make sure that the minimum features required to adhere to the 'standard' --e.g. header/footer menu collapsing (if that is, indeed, required to adhere to the standard)--are available without manually including these 3rd party assets.  

It's not a matter of size, rather, a matter of convenience. I wouldn't mind if the optional dependencies were all built into a single minimized/optimized package that is a part of the distribution. It'd be a lot easier for me to vendorize this into my own project that has its own front-end build lifecycle.

**Comment by rraub** [comment]
Related issues: #59 and #60
